[project]
name = "learn-ai"
version = "0.1.0"
description = "Agentic AI Tutor with Persistent Memory and RAG"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "openai",
    "streamlit",
    "python-dotenv"
]

[project.scripts]
learn-ai = "learn_ai.frontend.cli:run"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]